"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.activations import deserialize, elu, exponential, get, hard_sigmoid, linear, relu, selu, serialize, sigmoid, softmax, softplus, softsign, swish, tanh
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Built-in activation functions.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
