"""
This type stub file was generated by pyright.
"""

import sys as _sys
from . import experimental
from tensorflow.python.ops.summary_ops_v2 import SummaryWriter, create_file_writer_v2 as create_file_writer, create_noop_writer, flush, graph, record_if, should_record_summaries, trace_export, trace_off, trace_on, write

"""Operations for writing summary data, for use in analysis and visualization.

See the [Summaries and
TensorBoard](https://www.tensorflow.org/guide/summaries_and_tensorboard) guide.

"""
