"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.platform.tf_logging import DEBUG, ERROR, FATAL, INFO, TaskLevelStatusMessage, WARN, debug, error, fatal, flush, get_verbosity, info, log, log_every_n, log_first_n, log_if, set_verbosity, vlog, warn, warning

"""Logging and Summary Operations.
"""
