"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.autograph.core.ag_ctx import control_status_ctx
from tensorflow.python.autograph.impl.api import tf_convert

"""Public API for tf.__internal__.autograph namespace.
"""
