"""
This type stub file was generated by pyright.
"""

from keras.optimizers.optimizer_v2 import adadelta
from tensorflow.python.util.tf_export import keras_export

"""Legacy Adadelta optimizer implementation."""
@keras_export("keras.optimizers.legacy.Adadelta")
class Adadelta(adadelta.Adadelta):
    ...


