"""
This type stub file was generated by pyright.
"""

from keras.optimizers.optimizer_v2 import adagrad
from tensorflow.python.util.tf_export import keras_export

"""Legacy Adagrad optimizer implementation."""
@keras_export("keras.optimizers.legacy.Adagrad")
class Adagrad(adagrad.Adagrad):
    ...


