"""
This type stub file was generated by pyright.
"""

from keras.optimizers.optimizer_v2 import nadam
from tensorflow.python.util.tf_export import keras_export

"""Legacy Nadam optimizer implementation."""
@keras_export("keras.optimizers.legacy.Nadam")
class Nadam(nadam.Nadam):
    ...


