"""
This type stub file was generated by pyright.
"""

from keras.optimizers.optimizer_v2 import gradient_descent
from tensorflow.python.util.tf_export import keras_export

"""Legacy SGD optimizer implementation."""
@keras_export("keras.optimizers.legacy.SGD")
class SGD(gradient_descent.SGD):
    ...


