"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.applications.convnext import ConvNeXtBase, ConvNeXtLarge, ConvNeXtSmall, ConvNeXtTiny, ConvNeXtXLarge, decode_predictions, preprocess_input
from tensorflow.python.util import module_wrapper as _module_wrapper

"""ConvNeXt models for Keras.

References:

- [A ConvNet for the 2020s](https://arxiv.org/abs/2201.03545)
  (CVPR 2022)

"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
