"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.api.keras.__internal__.legacy import layers, rnn_cell
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf.keras.__internal__.legacy namespace.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
