"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.main_op_impl import main_op, main_op_with_restore

"""SavedModel main op.

Builds a main op that defines the sequence of ops to be run as part of the
SavedModel load/restore operations.

"""
