"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.applications.xception import Xception, decode_predictions, preprocess_input
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Xception V1 model for Keras.

On ImageNet, this model gets to a top-1 validation accuracy of 0.790
and a top-5 validation accuracy of 0.945.

Reference:
  - [Xception: Deep Learning with Depthwise Separable Convolutions](
      https://arxiv.org/abs/1610.02357) (CVPR 2017)

"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
