"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.mixed_precision.loss_scale_optimizer import BaseLossScaleOptimizer as LossScaleOptimizer
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Keras mixed precision API.

See [the mixed precision guide](
  https://www.tensorflow.org/guide/keras/mixed_precision) to learn how to
use the API.

"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
