"""
This type stub file was generated by pyright.
"""

from tensorflow.compat.v2.experimental import dtensor as dtensor_api

"""Keras' DTensor library."""
_DTENSOR_API_ENABLED = ...
if _DTENSOR_API_ENABLED:
    ...
else:
    dtensor_api = ...
