"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.ops.lookup_ops import DenseHashTable, MutableHashTable

"""Public API for tf.lookup.experimental namespace.
"""
