"""
This type stub file was generated by pyright.
"""

from tensorflow.python.ops.parallel_for import *
from tensorflow.python.ops.parallel_for.control_flow_ops import for_loop, pfor
from tensorflow.python.ops.parallel_for.gradients import batch_jacobian, jacobian

"""Ops for pfor, for_loop, jacobian."""
