"""
This type stub file was generated by pyright.
"""

from tensorflow.python.platform import test

"""Test utility."""
class PForTestCase(test.TestCase):
  """Base class for test cases."""
  def run_and_assert_equal(self, targets1, targets2, rtol=..., atol=...): # -> None:
    ...
  


