"""
This type stub file was generated by pyright.
"""

from ._base import BaseEnsemble
from ._forest import ExtraTreesClassifier, ExtraTreesRegressor, RandomForestClassifier, RandomForestRegressor, RandomTreesEmbedding
from ._bagging import BaggingClassifier, BaggingRegressor
from ._iforest import IsolationForest
from ._weight_boosting import AdaBoostClassifier, AdaBoostRegressor
from ._gb import GradientBoostingClassifier, GradientBoostingRegressor
from ._voting import VotingClassifier, VotingRegressor
from ._stacking import StackingClassifier, StackingRegressor
from ._hist_gradient_boosting.gradient_boosting import HistGradientBoostingClassifier, HistGradientBoostingRegressor

"""
The :mod:`sklearn.ensemble` module includes ensemble-based methods for
classification, regression and anomaly detection.
"""
__all__ = ["BaseEnsemble", "RandomForestClassifier", "RandomForestRegressor", "RandomTreesEmbedding", "ExtraTreesClassifier", "ExtraTreesRegressor", "BaggingClassifier", "BaggingRegressor", "IsolationForest", "GradientBoostingClassifier", "GradientBoostingRegressor", "AdaBoostClassifier", "AdaBoostRegressor", "VotingClassifier", "VotingRegressor", "StackingClassifier", "StackingRegressor", "HistGradientBoostingClassifier", "HistGradientBoostingRegressor"]
