"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.legacy_tf_layers.base import keras_style_scope, set_keras_style
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf.keras.__internal__.legacy.layers.experimental namespace.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
