"""
This type stub file was generated by pyright.
"""

from tensorflow.python.util.tf_export import tf_export

"""Implements the graph generation for computation of gradients."""
@tf_export("AggregationMethod")
class AggregationMethod:
  """A class listing aggregation methods used to combine gradients.

  Computing partial derivatives can require aggregating gradient
  contributions. This class lists the various methods that can
  be used to combine gradients in the graph.

  The following aggregation methods are part of the stable API for
  aggregating gradients:

  *  `ADD_N`: All of the gradient terms are summed as part of one
     operation using the "AddN" op (see `tf.add_n`). This
     method has the property that all gradients must be ready and
     buffered separately in memory before any aggregation is performed.
  *  `DEFAULT`: The system-chosen default aggregation method.

  The following aggregation methods are experimental and may not
  be supported in future releases:

  * `EXPERIMENTAL_TREE`: Gradient terms are summed in pairs using
    the "AddN" op. This method of summing gradients may reduce
    performance, but it can improve memory utilization because the
    gradients can be released earlier.

  """
  ADD_N = ...
  DEFAULT = ...
  EXPERIMENTAL_TREE = ...
  EXPERIMENTAL_ACCUMULATE_N = ...


POSSIBLE_GRADIENT_TYPES_NONE = ...
POSSIBLE_GRADIENT_TYPES_FIRST_ORDER = ...
POSSIBLE_GRADIENT_TYPES_HIGHER_ORDER = ...
def PossibleTapeGradientTypes(tensors):
  """Determines whether and how `args` may require tape gradients."""
  ...

