"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.ops.array_ops import gather_nd, reshape
from tensorflow.python.ops.gen_array_ops import batch_to_space_nd, reverse_v2 as reverse, scatter_nd, space_to_batch_nd, tile
from tensorflow.python.ops.manip_ops import roll

"""Operators for manipulating tensors.
"""
