"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.profiler.model_analyzer import Profiler, advise, profile
from tensorflow.python.profiler.option_builder import ProfileOptionBuilder
from tensorflow.python.profiler.profiler import AdviceProto, GraphNodeProto, MultiGraphNodeProto, OpLogProto
from tensorflow.python.profiler.tfprof_logger import write_op_log

"""Public API for tf.profiler namespace.
"""
