"""
This type stub file was generated by pyright.
"""

from tensorflow.python.util import tf_contextlib

"""Metrics collecting utilities for single client training."""
enable_metrics = ...
_METRICS_MAPPING = ...
@tf_contextlib.contextmanager
def monitored_timer(metric_name, state_tracker=...): # -> Generator[None, None, None]:
  """Monitor the execution time and collect it into the specified metric."""
  ...

def get_metric_summary(metric_name): # -> dict[Unknown, Unknown]:
  """Get summary for the specified metric."""
  ...

