"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.api._v2.keras.callbacks import experimental
from keras.callbacks import BackupAndRestore, BaseLogger, CSVLogger, Callback, CallbackList, EarlyStopping, History, LambdaCallback, LearningRateScheduler, ModelCheckpoint, ProgbarLogger, ReduceLROnPlateau, RemoteMonitor, TensorBoard, TerminateOnNaN

"""Callbacks: utilities called at certain points during model training.
"""
