"""
This type stub file was generated by pyright.
"""

from keras.layers.attention.additive_attention import AdditiveAttention
from keras.layers.attention.attention import Attention
from keras.layers.attention.multi_head_attention import MultiHeadAttention

"""Keras attention layers."""
