"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.lib.io.tf_record import TFRecordCompressionType, TFRecordOptions, TFRecordWriter, tf_record_iterator

"""Python functions for directly manipulating TFRecord-formatted files.
"""
