"""
This type stub file was generated by pyright.
"""

import os
import platform
import sys
import typing
import subprocess
from typing import Literal

"""Python 3.7 to 3.8 compatibility and platform compatibility."""
PY38 = ...
Literal: typing.Any
if PY38:
    Literal = ...
else:
    Literal = ...
def get_startupinfo() -> None:
    """Return None for startupinfo argument of ``subprocess.Popen``."""
    ...

if platform.system() == 'Windows':
    def get_startupinfo() -> subprocess.STARTUPINFO:
        """Return subprocess.STARTUPINFO instance hiding the console window."""
        ...
    
def make_subprocess_arg(arg: typing.Union[str, os.PathLike]) -> typing.Union[str, os.PathLike]:
    """Return subprocess argument as is (default no-op)."""
    ...

if platform.system() == 'Windows' and sys.version_info < (3, 8):
    ...
