"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.constants import ASSETS_DIRECTORY, ASSETS_KEY, DEBUG_DIRECTORY, DEBUG_INFO_FILENAME_PB, LEGACY_INIT_OP_KEY, MAIN_OP_KEY, SAVED_MODEL_FILENAME_PB, SAVED_MODEL_FILENAME_PBTXT, SAVED_MODEL_SCHEMA_VERSION, VARIABLES_DIRECTORY, VARIABLES_FILENAME

"""Constants for SavedModel save and restore operations.

The source of truth for these constants is in
tensorflow/cc/saved_model/constants.h.


"""
