"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.engine.base_layer import BaseRandomLayer
from keras.layers.preprocessing.image_preprocessing import BaseImageAugmentationLayer

"""Public API for tf.keras.__internal__.layers namespace.
"""
