"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.layers.rnn.legacy_cell_wrappers import DeviceWrapper, DropoutWrapper, ResidualWrapper
from keras.layers.rnn.legacy_cells import BasicLSTMCell, BasicRNNCell, GRUCell, LSTMCell, LSTMStateTuple, MultiRNNCell, RNNCell
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf.keras.__internal__.legacy.rnn_cell namespace.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
