"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.feature_column.feature_column_v2 import DenseColumn, FeatureColumn, FeatureTransformationCache, SequenceDenseColumn, _StateManagerImpl as StateManager
from tensorflow.python.feature_column.serialization import deserialize_feature_column, serialize_feature_column

"""Public API for tf.__internal__.feature_column namespace.
"""
