"""
This type stub file was generated by pyright.
"""

"""A Python wrapper that loads _pywrap_tensorflow_internal.so."""
_can_set_rtld_local = ...
if _can_set_rtld_local:
  _default_dlopen_flags = ...
