"""
This type stub file was generated by pyright.
"""

class DrawTree:
    def __init__(self, tree, parent=..., depth=..., number=...) -> None:
        ...
    
    def left(self): # -> int | DrawTree:
        ...
    
    def right(self): # -> int | DrawTree:
        ...
    
    def lbrother(self): # -> None:
        ...
    
    def get_lmost_sibling(self): # -> None:
        ...
    
    lmost_sibling = ...
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def max_extents(self):
        ...
    


def buchheim(tree): # -> DrawTree:
    ...

def third_walk(tree, n): # -> None:
    ...

def first_walk(v, distance=...):
    ...

def apportion(v, default_ancestor, distance):
    ...

def move_subtree(wl, wr, shift): # -> None:
    ...

def execute_shifts(v): # -> None:
    ...

def ancestor(vil, v, default_ancestor):
    ...

def second_walk(v, m=..., depth=..., min=...):
    ...

class Tree:
    def __init__(self, label=..., node_id=..., *children) -> None:
        ...
    


