"""
This type stub file was generated by pyright.
"""

import tensorflow.compat.v2 as tf
from keras.layers.rnn.abstract_rnn_cell import AbstractRNNCell
from keras.layers.rnn.base_rnn import RNN
from keras.layers.rnn.simple_rnn import SimpleRNN, SimpleRNNCell
from keras.layers.rnn.stacked_rnn_cells import StackedRNNCells
from keras.layers.rnn.gru import GRU, GRUCell
from keras.layers.rnn.gru_v1 import GRU as GRUV1, GRUCell as GRUCellV1
from keras.layers.rnn.lstm import LSTM, LSTMCell
from keras.layers.rnn.lstm_v1 import LSTM as LSTMV1, LSTMCell as LSTMCellV1
from keras.layers.rnn.base_wrapper import Wrapper
from keras.layers.rnn.bidirectional import Bidirectional
from keras.layers.rnn.cell_wrappers import DeviceWrapper, DropoutWrapper, ResidualWrapper
from keras.layers.rnn.conv_lstm1d import ConvLSTM1D
from keras.layers.rnn.conv_lstm2d import ConvLSTM2D
from keras.layers.rnn.conv_lstm3d import ConvLSTM3D
from keras.layers.rnn.cudnn_gru import CuDNNGRU
from keras.layers.rnn.cudnn_lstm import CuDNNLSTM
from keras.layers.rnn.time_distributed import TimeDistributed

"""Keras recurrent layers."""
if tf.__internal__.tf2.enabled():
    GRUV2 = ...
    GRUCellV2 = ...
    LSTMV2 = ...
    LSTMCellV2 = ...
else:
    GRUV1 = ...
    GRUCellV1 = ...
    LSTMV1 = ...
    LSTMCellV1 = ...
