"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.utils_impl import build_tensor_info, get_tensor_from_tensor_info

"""SavedModel utility functions.

Utility functions to assist with setup and construction of the SavedModel proto.

"""
