"""
This type stub file was generated by pyright.
"""

import sys as _sys
from . import experimental
from tensorflow.lite.python.lite import Interpreter, OpsSet, Optimize, RepresentativeDataset, TFLiteConverterV2 as TFLiteConverter, TargetSpec

"""Public API for tf.lite namespace.
"""
