"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.activations import deserialize, elu, exponential, gelu, get, hard_sigmoid, linear, relu, selu, serialize, sigmoid, softmax, softplus, softsign, swish, tanh

"""Built-in activation functions.
"""
