"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.ops.gen_bitwise_ops import bitwise_and, bitwise_or, bitwise_xor, invert, left_shift, right_shift

"""Operations for manipulating the binary representations of integers.
"""
