"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.builder_impl import SavedModelBuilder

"""SavedModel builder.

Builds a SavedModel that can be saved to storage, is language neutral, and
enables systems to produce, consume, or transform TensorFlow Models.


"""
