"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.framework.graph_util_impl import convert_variables_to_constants, extract_sub_graph, must_run_on_cpu, remove_training_nodes, tensor_shape_from_node_def_name
from tensorflow.python.framework.importer import import_graph_def

"""Helpers to manipulate a tensor graph in python.

"""
