"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.ops.sets_impl import set_difference, set_intersection, set_size, set_union

"""Tensorflow set operations.
"""
