"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.training.experimental.loss_scale import DynamicLossScale, FixedLossScale, LossScale

"""Public API for tf.mixed_precision.experimental namespace.
"""
