"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.applications.mobilenet_v3 import decode_predictions, preprocess_input
from tensorflow.python.util import module_wrapper as _module_wrapper

"""MobileNet v3 models for Keras.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
