"""
This type stub file was generated by pyright.
"""

"""SignatureDef utility functions implementation."""
def supervised_train_signature_def(inputs, loss, predictions=..., metrics=...):
    ...

def supervised_eval_signature_def(inputs, loss, predictions=..., metrics=...):
    ...

