"""
This type stub file was generated by pyright.
"""

"""Logical boolean operators: not, and, or."""
def not_(a): # -> _dispatcher_for_logical_not | object | bool:
  """Functional form of "not"."""
  ...

def and_(a, b): # -> Any | list[Unknown] | _basetuple | defaultdict[Unknown, Unknown] | ObjectProxy:
  """Functional form of "and". Uses lazy evaluation semantics."""
  ...

def or_(a, b): # -> Any | list[Unknown] | _basetuple | defaultdict[Unknown, Unknown] | ObjectProxy:
  """Functional form of "or". Uses lazy evaluation semantics."""
  ...

def eq(a, b):
  """Functional form of "equal"."""
  ...

def not_eq(a, b): # -> _dispatcher_for_logical_not | object | bool:
  """Functional form of "not-equal"."""
  ...

