"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.backend import _initialize_variables as initialize_variables, track_variable

"""Public API for tf.keras.__internal__.backend namespace.
"""
