"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.applications.vgg16 import VGG16, decode_predictions, preprocess_input
from tensorflow.python.util import module_wrapper as _module_wrapper

"""VGG16 model for Keras.

Reference:
  - [Very Deep Convolutional Networks for Large-Scale Image Recognition]
    (https://arxiv.org/abs/1409.1556) (ICLR 2015)

"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
