"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.applications.inception_resnet_v2 import InceptionResNetV2, decode_predictions, preprocess_input
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Inception-ResNet V2 model for Keras.

Reference:
  - [Inception-v4, Inception-ResNet and the Impact of
     Residual Connections on Learning](https://arxiv.org/abs/1602.07261)
    (AAAI 2017)

"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
