"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.ops.summary_ops_v2 import get_step, set_step, summary_scope, write_raw_pb

"""Public API for tf.summary.experimental namespace.
"""
