"""
This type stub file was generated by pyright.
"""

from tensorflow.python.util import deprecation
from tensorflow.python.util.tf_export import tf_export

"""SavedModel utility functions implementation."""
@tf_export(v1=["saved_model.build_tensor_info", "saved_model.utils.build_tensor_info"])
@deprecation.deprecated(None, "This function will only be available through the v1 compatibility " "library as tf.compat.v1.saved_model.utils.build_tensor_info or " "tf.compat.v1.saved_model.build_tensor_info.")
def build_tensor_info(tensor): # -> TensorInfo:
  """Utility function to build TensorInfo proto from a Tensor.

  Args:
    tensor: Tensor or SparseTensor whose name, dtype and shape are used to
        build the TensorInfo. For SparseTensors, the names of the three
        constituent Tensors are used.

  Returns:
    A TensorInfo protocol buffer constructed based on the supplied argument.

  Raises:
    RuntimeError: If eager execution is enabled.

  @compatibility(TF2)
  This API is not compatible with eager execution as `tensor` needs to be a
  graph tensor, and there is no replacement for it in TensorFlow 2.x. To start
  writing programs using TensorFlow 2.x, please refer to the [Effective
  TensorFlow 2](https://www.tensorflow.org/guide/effective_tf2) guide.
  @end_compatibility
  """
  ...

def build_tensor_info_internal(tensor): # -> TensorInfo:
  """Utility function to build TensorInfo proto from a Tensor."""
  ...

def build_tensor_info_from_op(op): # -> TensorInfo:
  """Utility function to build TensorInfo proto from an Op.

  Note that this function should be used with caution. It is strictly restricted
  to TensorFlow internal use-cases only. Please make sure you do need it before
  using it.

  This utility function overloads the TensorInfo proto by setting the name to
  the Op's name, dtype to DT_INVALID and tensor_shape as None. One typical usage
  is for the Op of the call site for the defunned function:
  ```python
    @function.defun
    def some_variable_initialization_fn(value_a, value_b):
      a = value_a
      b = value_b

    value_a = constant_op.constant(1, name="a")
    value_b = constant_op.constant(2, name="b")
    op_info = utils.build_op_info(
        some_variable_initialization_fn(value_a, value_b))
  ```

  Args:
    op: An Op whose name is used to build the TensorInfo. The name that points
        to the Op could be fetched at run time in the Loader session.

  Returns:
    A TensorInfo protocol buffer constructed based on the supplied argument.

  Raises:
    RuntimeError: If eager execution is enabled.
  """
  ...

@tf_export(v1=["saved_model.get_tensor_from_tensor_info", "saved_model.utils.get_tensor_from_tensor_info"])
@deprecation.deprecated(None, "This function will only be available through the v1 compatibility " "library as tf.compat.v1.saved_model.utils.get_tensor_from_tensor_info or " "tf.compat.v1.saved_model.get_tensor_from_tensor_info.")
def get_tensor_from_tensor_info(tensor_info, graph=..., import_scope=...): # -> Tensor | Operation | SparseTensor | defaultdict[Unknown, Unknown] | Any | list[Unknown] | ObjectProxy | None:
  """Returns the Tensor or CompositeTensor described by a TensorInfo proto.

  Args:
    tensor_info: A TensorInfo proto describing a Tensor or SparseTensor or
      CompositeTensor.
    graph: The tf.Graph in which tensors are looked up. If None, the
        current default graph is used.
    import_scope: If not None, names in `tensor_info` are prefixed with this
        string before lookup.

  Returns:
    The Tensor or SparseTensor or CompositeTensor in `graph` described by
    `tensor_info`.

  Raises:
    KeyError: If `tensor_info` does not correspond to a tensor in `graph`.
    ValueError: If `tensor_info` is malformed.
  """
  ...

def get_element_from_tensor_info(tensor_info, graph=..., import_scope=...): # -> Tensor | Operation | None:
  """Returns the element in the graph described by a TensorInfo proto.

  Args:
    tensor_info: A TensorInfo proto describing an Op or Tensor by name.
    graph: The tf.Graph in which tensors are looked up. If None, the current
      default graph is used.
    import_scope: If not None, names in `tensor_info` are prefixed with this
      string before lookup.

  Returns:
    Op or tensor in `graph` described by `tensor_info`.

  Raises:
    KeyError: If `tensor_info` does not correspond to an op or tensor in `graph`
  """
  ...

def get_or_create_variables_dir(export_dir): # -> LiteralString:
  """Return variables sub-directory, or create one if it doesn't exist."""
  ...

def get_variables_dir(export_dir): # -> LiteralString:
  """Return variables sub-directory in the SavedModel."""
  ...

def get_variables_path(export_dir): # -> LiteralString:
  """Return the variables path, used as the prefix for checkpoint files."""
  ...

def get_or_create_assets_dir(export_dir): # -> LiteralString:
  """Return assets sub-directory, or create one if it doesn't exist."""
  ...

def get_assets_dir(export_dir): # -> LiteralString:
  """Return path to asset directory in the SavedModel."""
  ...

def get_or_create_debug_dir(export_dir): # -> LiteralString:
  """Returns path to the debug sub-directory, creating if it does not exist."""
  ...

def get_saved_model_pbtxt_path(export_dir): # -> LiteralString:
  ...

def get_saved_model_pb_path(export_dir): # -> LiteralString:
  ...

def get_debug_dir(export_dir): # -> LiteralString:
  """Returns path to the debug sub-directory in the SavedModel."""
  ...

byte_swappable = ...
def swap_function_tensor_content(meta_graph_def, from_endiness, to_endiness): # -> None:
  ...

def byte_swap_tensor_content(tensor, from_endiness, to_endiness): # -> None:
  """Byte swaps."""
  ...

