"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.api._v2.keras.dtensor.experimental import optimizers
from keras.dtensor.layout_map import LayoutMap, layout_map_scope

"""Public API for tf.keras.dtensor.experimental namespace.
"""
