"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.compiler.mlir.mlir import convert_function, convert_graph_def

"""Public API for tf.mlir.experimental namespace.
"""
