"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.save import save
from tensorflow.python.saved_model.save_options import VariablePolicy
from tensorflow.python.trackable.resource import TrackableResource

"""Public API for tf.saved_model.experimental namespace.
"""
