"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.wrappers.scikit_learn import KerasClassifier, KerasRegressor

"""Wrapper for using the Scikit-Learn API with Keras models.
"""
