"""
This type stub file was generated by pyright.
"""

from keras.layers.locally_connected.locally_connected1d import LocallyConnected1D
from keras.layers.locally_connected.locally_connected2d import LocallyConnected2D

"""Keras locally-connected layers."""
