"""
This type stub file was generated by pyright.
"""

import sys as _sys
from keras.estimator import model_to_estimator
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Keras estimator API.
"""
if notisinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
