"""
This type stub file was generated by pyright.
"""

import json

"""Utils for creating and loading the Layer metadata for SavedModel.

These are required to retain the original format of the build input shape, since
layers and models may have different build behaviors depending on if the shape
is a list, tuple, or TensorShape. For example, Network.build() will create
separate inputs if the given input_shape is a list, and will create a single
input if the given shape is a tuple.
"""
_EXTENSION_TYPE_SPEC = ...
class Encoder(json.JSONEncoder):
    """JSON encoder and decoder that handles TensorShapes and tuples."""
    def default(self, obj): # -> dict[str, Unknown] | Any | dict[Unknown, Unknown] | dict[str, str] | None:
        """Encodes objects for types that aren't handled by the default
        encoder."""
        ...
    
    def encode(self, obj): # -> str:
        ...
    


def decode(json_string): # -> Any:
    ...

def decode_and_deserialize(json_string, module_objects=..., custom_objects=...): # -> Any:
    """Decodes the JSON and deserializes any Keras objects found in the dict."""
    ...

def get_json_type(obj): # -> Any | dict[str, Unknown] | dict[Unknown, Unknown] | dict[str, str] | None:
    """Serializes any object to a JSON-serializable structure.

    Args:
        obj: the object to serialize

    Returns:
        JSON-serializable structure representing `obj`.

    Raises:
        TypeError: if `obj` cannot be serialized.
    """
    ...

