"""
This type stub file was generated by pyright.
"""

import collections.abc

"""A set based on dict so that it preserves key insertion order.

Python Dicts are order-preserving since 3.6
(https://mail.python.org/pipermail/python-dev/2017-December/151283.html),
but sets are not. This class implements a set on top of a dict so that we get
deterministic iteration order across runs.
"""
class OrderPreservingSet(collections.abc.MutableSet):
    """A set based on dict so that it preserves key insertion order."""
    def __init__(self, iterable=...) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, value): # -> bool:
        ...
    
    def __iter__(self): # -> Iterator[Unknown | Any]:
        ...
    
    def add(self, item): # -> None:
        ...
    
    def discard(self, value): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __le__(self, other) -> bool:
        ...
    
    def __ge__(self, other) -> bool:
        ...
    
    def __and__(self, other):
        ...
    
    def __or__(self, other):
        ...
    
    def union(self, other):
        ...
    


